title: walkah
author: James Walker
description: "James Walker is an independent developer and hacker"
url: http://walkah.net

highlighter: pygments
lsi: true
markdown: redcarpet
permalink: blog/:title
exclude: 
  - Gemfile
  - Gemfile.lock
  - Rakefile
