title: walkah
author: James Walker
description: "James Walker is an independent developer and hacker"
url: https://walkah.net

markdown: kramdown
permalink: blog/:title/
exclude: [Gemfile, Gemfile.lock, vendor]

sass:
  style: compressed

plugins:
  - bourbon
  - neat 
  - jekyll-gist
