title: walkah
author: James Walker
description: "James Walker is an independent developer and hacker"
url: http://walkah.net

pygments: true
lsi: false
markdown: kramdown
permalink: blog/:title
exclude: 
  - Gemfile
  - Gemfile.lock
  - Rakefile
